dynamodb:
  image: savaki/dynamodb:latest
  ports:
    - "8000:8000"

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=eventsource
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=eventsource

postgres:
  image: postgres:9.6-alpine
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=eventsource
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=eventsource
